export type ScreenId =
  | "dashboard"
  | "transactions"
  | "goals"
  | "buckets"
  | "coach"
  | "profile"
  | "budgets"
  | "subscriptions"
  | "health"
  | "emergency"
  | "reports"
  | "review"
  | "loans"
  | "categories"
  | "accounts"
  | "documents"
  | "tax"
  | "security"
  | "privacy"
  | "networth"
  | "timeline"
  | "calendar"
  | "notifications"
  | "family"
  | "leakage"
  | "inflation"
  | "fire"
  | "simulator"
  | "import"
  | "feedback"
  | "cash"
  | "sip"
  | "insurance"
  | "investments"
  | "gold"
  | "property"
  | "creditscore"
  | "fraud"
  | "pricing"
  | "news"
  | "itr-filing"
  | "privacy-policy"
  | "terms"
  | "contact"
  | "data-safety"
  | "cloud-backup";


export const inr = (n: number) =>
  "₹" + Math.abs(n).toLocaleString("en-IN", { maximumFractionDigits: 0 });
