export type ScreenId =
  | "dashboard"
  | "transactions"
  | "goals"
  | "coach"
  | "profile"
  | "budgets"
  | "subscriptions"
  | "health"
  | "emergency"
  | "reports"
  | "review"
  | "loans"
  | "categories"
  | "accounts"
  | "documents"
  | "tax"
  | "security"
  | "privacy"
  | "networth"
  | "timeline"
  | "calendar"
  | "notifications"
  | "family"
  | "leakage"
  | "inflation"
  | "fire"
  | "simulator"
  | "import"
  | "pricing"
  | "feedback"
  | "cash";

export const inr = (n: number) =>
  "₹" + Math.abs(n).toLocaleString("en-IN", { maximumFractionDigits: 0 });
